server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth
          uri: ${TARGET_AUTH:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: catalog
          uri: ${TARGET_CATALOG:http://localhost:8082}
          predicates:
            - Path=/catalog/**
        - id: inventory
          uri: ${TARGET_INVENTORY:http://localhost:8083}
          predicates:
            - Path=/inventory/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
jwt:
  secret: ${JWT_SECRET:devsecretdevsecretdevsecretdevsecret}
